#pragma once

#include <cstddef>
#include <cstdint>
#include <deque>
#include <map>
#include <optional>
#include <string>
#include <utility>
#include <vector>

#include <vterm.h>

namespace pmux {

// Terminal state libvterm does not expose, tracked over the raw output stream.
// The escape-sequence parser state survives chunk boundaries.
class ModeTracker {
 public:
  // Returns the bytes consumed: stops right after a sequence that enters the alternate
  // screen (see take_alt_request), else consumes everything.
  std::size_t feed(const char* data, std::size_t len);
  bool take_alt_request() { return std::exchange(alt_requested_, false); }
  void reset();

  // Mode restore sequences (keys, mouse, paste, cursor shape, cursor visibility last).
  // Without `input`, only the cursor shape and visibility.
  std::string restore_modes(bool input) const;
  // Kitty keyboard flags push for the main / alternate screen stack ("" if none).
  std::string restore_kitty(bool alt) const;
  // Title (OSC 2) and recorded OSC 4/10/11/12 color sets.
  std::string restore_title_and_colors() const;
  // OSC 104;<idx> / 110 / 111 / 112 for colors the app set and has not reset.
  std::string color_resets() const;

 private:
  enum class State { Ground, Esc, EscIntermediate, Csi, Osc, OscEsc, String, StringEsc };

  void dispatch_csi(char final);
  void dispatch_osc();
  void dispatch_esc(char final);
  void set_private_mode(int mode, bool on);
  std::string restore_input_modes() const;
  std::vector<std::uint32_t>& kitty_stack() { return alt_ ? kitty_alt_ : kitty_main_; }

  State state_ = State::Ground;
  std::string params_;
  char prefix_ = 0;
  std::string intermediates_;
  std::string osc_;
  bool osc_overflow_ = false;
  bool alt_requested_ = false;

  // Tracked state.
  bool alt_ = false;
  bool cursor_keys_ = false;  // DECCKM (?1)
  bool autowrap_ = true;      // DECAWM (?7)
  bool cursor_visible_ = true;
  bool keypad_ = false;  // ESC = / ESC >
  bool focus_ = false;   // ?1004
  bool paste_ = false;   // ?2004
  int mouse_ = 0;  // 1000 / 1002 / 1003 (mutually exclusive), 0 = off
  bool mouse_1005_ = false, mouse_1006_ = false, mouse_1015_ = false;
  int cursor_shape_ = -1;  // DECSCUSR Ps; -1 = never set
  std::vector<std::uint32_t> kitty_main_{0}, kitty_alt_{0};  // back() = current flags
  std::optional<std::string> title_;
  std::map<int, std::string> palette_;  // OSC 4 index -> spec
  std::optional<std::string> dyn_colors_[3];  // OSC 10 / 11 / 12
};

// Rewrites SGR sequences in the stream fed to libvterm (never the bytes sent to a client).
// libvterm 0.3.3 has no faint attribute, so faint is carried in the alternate font slot:
// SGR 2 -> 11 (font 1), SGR 22 -> 22;10 (normal intensity also clears faint); resets clear
// the font already. Also drops underline colors (58, which libvterm misreads as further SGR
// parameters) and the color-space id of `38:2:<cs>:r:g:b` / `48:...`, and keeps every CSI
// within libvterm's 16-argument limit (more crash libvterm 0.3.3; long SGRs are split, other
// sequences truncated). Other bytes pass through unchanged; parser state survives chunk
// boundaries (a partial CSI is held back).
class SgrRewriter {
 public:
  void feed(const char* data, std::size_t len, std::string& out);

 private:
  enum class State { Ground, Esc, EscIntermediate, Csi, CsiPass, String, StringEsc };
  void finish_csi(char final, std::string& out);
  // Counts argument separators; false for parameter bytes past libvterm's argument limit.
  bool keep_param_byte(char ch);

  State state_ = State::Ground;
  std::string raw_;     // the pending CSI, verbatim (from ESC [)
  std::string params_;  // its parameter bytes
  std::string c0_;      // C0 controls executed inside it
  int separators_ = 0;  // ';' and ':' seen in it
  bool rewritable_ = true;
};

// Per-session virtual terminal: libvterm screen, scrollback ring, mode tracker.
class Screen {
 public:
  Screen(int rows, int cols, std::size_t scrollback_lines = 10000);
  ~Screen();
  Screen(const Screen&) = delete;
  Screen& operator=(const Screen&) = delete;

  // Feeds PTY output. Terminal query replies generated by libvterm accumulate in replies().
  void feed(const char* data, std::size_t len);
  void resize(int rows, int cols);
  // Bytes that redraw the screen, history and modes on a freshly attached terminal.
  // Non-interactive (read-only view): input-related modes and kitty flags are not restored.
  std::string snapshot(bool interactive);
  std::string color_resets() const { return modes_.color_resets(); }

  std::string take_replies() { return std::exchange(replies_, {}); }
  bool take_bell() { return std::exchange(bell_, false); }

  // Compact cell storage (public for the libvterm callbacks in screen.cpp).
  struct Pen {
    std::uint16_t flags = 0;  // bit set, see screen.cpp
    std::uint8_t underline = 0;
    std::uint32_t fg = 0;  // packed VTermColor
    std::uint32_t bg = 0;
    bool operator==(const Pen&) const = default;
  };
  struct Line {
    std::vector<std::uint32_t> chars;  // one per cell: 0 empty, 0xFFFFFFFF wide-char continuation
    std::vector<std::pair<std::uint16_t, Pen>> runs;  // (start column, pen), ascending
    std::vector<std::pair<std::uint16_t, std::u32string>> combining;  // extra codepoints per column
  };

  void push_line(Line line);
  bool pop_line(Line& line);
  void clear_scrollback() { scrollback_.clear(); }
  void set_alt(bool alt) { alt_ = alt; }
  void ring_bell() { bell_ = true; }
  void add_reply(const char* data, std::size_t len) { replies_.append(data, len); }
  std::uint32_t default_fg() const;  // packed VTermColor
  std::uint32_t default_bg() const;

 private:
  Line read_row(int row) const;

  VTerm* vt_ = nullptr;
  VTermScreen* screen_ = nullptr;
  VTermState* state_ = nullptr;
  int rows_;
  int cols_;
  std::size_t capacity_;
  std::deque<Line> scrollback_;
  std::vector<Line> saved_primary_;  // primary screen rows when the alternate screen was entered
  VTermPos saved_cursor_{};
  ModeTracker modes_;
  SgrRewriter sgr_;
  std::string rewritten_;  // scratch for feed()
  std::string replies_;
  bool bell_ = false;
  bool alt_ = false;
};

}  // namespace pmux
